package com.jean.models;

import java.io.Serializable;

public class BizCity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_city.CITY_ID
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_city.CITY_EN_NAME
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    private String cityEnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_city.CITY_CN_NAME
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    private String cityCnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_city.CITY_SHORT_NAME
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    private String cityShortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_city.CITY_AB_NAME
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    private String cityAbName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_city.PROVINCE_ID
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    private Integer provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_city.PROVINCE_NAME
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_city.STATE
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_city.COUNTRY_ID
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    private Double countryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_city.COUNTRY_NAME
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    private String countryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_city
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_city.CITY_ID
     *
     * @return the value of biz_city.CITY_ID
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_city.CITY_ID
     *
     * @param cityId the value for biz_city.CITY_ID
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_city.CITY_EN_NAME
     *
     * @return the value of biz_city.CITY_EN_NAME
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public String getCityEnName() {
        return cityEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_city.CITY_EN_NAME
     *
     * @param cityEnName the value for biz_city.CITY_EN_NAME
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public void setCityEnName(String cityEnName) {
        this.cityEnName = cityEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_city.CITY_CN_NAME
     *
     * @return the value of biz_city.CITY_CN_NAME
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public String getCityCnName() {
        return cityCnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_city.CITY_CN_NAME
     *
     * @param cityCnName the value for biz_city.CITY_CN_NAME
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public void setCityCnName(String cityCnName) {
        this.cityCnName = cityCnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_city.CITY_SHORT_NAME
     *
     * @return the value of biz_city.CITY_SHORT_NAME
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public String getCityShortName() {
        return cityShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_city.CITY_SHORT_NAME
     *
     * @param cityShortName the value for biz_city.CITY_SHORT_NAME
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public void setCityShortName(String cityShortName) {
        this.cityShortName = cityShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_city.CITY_AB_NAME
     *
     * @return the value of biz_city.CITY_AB_NAME
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public String getCityAbName() {
        return cityAbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_city.CITY_AB_NAME
     *
     * @param cityAbName the value for biz_city.CITY_AB_NAME
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public void setCityAbName(String cityAbName) {
        this.cityAbName = cityAbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_city.PROVINCE_ID
     *
     * @return the value of biz_city.PROVINCE_ID
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_city.PROVINCE_ID
     *
     * @param provinceId the value for biz_city.PROVINCE_ID
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_city.PROVINCE_NAME
     *
     * @return the value of biz_city.PROVINCE_NAME
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_city.PROVINCE_NAME
     *
     * @param provinceName the value for biz_city.PROVINCE_NAME
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_city.STATE
     *
     * @return the value of biz_city.STATE
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_city.STATE
     *
     * @param state the value for biz_city.STATE
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_city.COUNTRY_ID
     *
     * @return the value of biz_city.COUNTRY_ID
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public Double getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_city.COUNTRY_ID
     *
     * @param countryId the value for biz_city.COUNTRY_ID
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public void setCountryId(Double countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_city.COUNTRY_NAME
     *
     * @return the value of biz_city.COUNTRY_NAME
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_city.COUNTRY_NAME
     *
     * @param countryName the value for biz_city.COUNTRY_NAME
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }
}