package com.jean.mapper;

import com.jean.models.BizCity;

public interface BizCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_city
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    int deleteByPrimaryKey(Integer cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_city
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    int insert(BizCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_city
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    int insertSelective(BizCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_city
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    BizCity selectByPrimaryKey(Integer cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_city
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    int updateByPrimaryKeySelective(BizCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_city
     *
     * @mbg.generated Sun Apr 16 17:13:08 CST 2017
     */
    int updateByPrimaryKey(BizCity record);
}